[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/renderer"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200