[build]
  command = "npm run build"
  publish = "dist"

# Enforce Netlify to pass all route handling to TanStack Client-Side Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"